jdbldDirectory = _jdbld

javaHome = /usr/lib/jvm/java-25

# extensionsSnapshotRepository = \
#     https://central.sonatype.com/repository/maven-snapshots/
extensionsSnapshotRepository = \
    https://codeberg.org/api/packages/JDrupes/maven/
buildExtensions = org.jdrupes.gitversioning:core:0.6.0
