/*
 * JDrupes GitVersioning
 * Copyright (C) 2025 Michael N. Lipp
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.jdrupes.gitversioning.core;

import com.vdurmont.semver4j.Semver;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Pattern;
import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.diff.DiffEntry;
import org.eclipse.jgit.lib.Repository;
import org.eclipse.jgit.revwalk.RevCommit;
import org.eclipse.jgit.revwalk.RevWalk;
import org.eclipse.jgit.treewalk.CanonicalTreeParser;
import org.jdrupes.gitversioning.api.VersionEvaluator;

/**
 * A maven style tag processor.
 * 
 * If the (latest) version found ends with "{@code -SNAPSHOT}", this
 * version is returned unchanged.
 * 
 * If there have been no commits that changed files in the relevant
 * sub-directory since the tag was created, and no untracked
 * ("dirty") files exist in that sub-directory, the version found
 * is returned unchanged.
 * 
 * Else a new version is generated by incrementing the patch number
 * of the version found, optionally appending the normalized branch
 * name and "{@code -SNAPSHOT}".
 * 
 * The branch name is omitted from the version if it matches one of the
 * patterns in ignored branches (by default "main" and "master").
 * Normalization replaces all characters except letters, numbers and
 * underscore with underscores.
 */
public class MavenStyleTagProcessor extends TagProcessorBase {

    private static final List<Pattern> DEFAULT_PATTERNS
        = List.of(Pattern.compile("main"), Pattern.compile("master"));
    private List<Pattern> ignoredBranches = new ArrayList<>();

    /**
     * Instantiates a new maven style tag processor.
     */
    public MavenStyleTagProcessor() {
        ignoredBranches.addAll(DEFAULT_PATTERNS);
    }

    /**
     * Sets the regex patterns for branch names that should be ignored.
     *
     * @param patterns the patterns
     * @return the maven style tag processor
     */
    public MavenStyleTagProcessor ignoredBranches(String... patterns) {
        ignoredBranches = new ArrayList<>(
            Arrays.stream(patterns).map(Pattern::compile).toList());
        return this;
    }

    /**
     * Adds the given regex patterns to the list of branch name patterns
     * to ignore.
     *
     * @param patterns the patterns
     * @return the maven style tag processor
     */
    public MavenStyleTagProcessor ignoreBranches(String... patterns) {
        ignoredBranches
            .addAll(Arrays.stream(patterns).map(Pattern::compile).toList());
        return this;
    }

    @Override
    public String version(Repository repository, Path subDir, RevCommit commit,
            String tagName, String version)
            throws IOException, GitAPIException {
        if (version.endsWith("-SNAPSHOT")) {
            return version;
        }
        if (subDir == null) {
            subDir = Path.of("");
        }
        subDir = VersionEvaluatorProvider
            .relativizeDirectory(repository, subDir);
        if (commit != null && isVersionClean(repository, subDir, commit)) {
            return version;
        }

        // Need new version
        Semver semver
            = new Semver(version, Semver.SemverType.LOOSE).nextPatch();
        StringBuilder newVersion = new StringBuilder(semver.toString());
        var branch = repository.getBranch();
        if (!ignoredBranches.stream().map(p -> p.matcher(branch).matches())
            .filter(b -> b).findAny().isPresent()) {
            newVersion.append('-')
                .append(branch.replaceAll("[^_A-Za-z0-9]", "_"));
        }
        newVersion.append("-SNAPSHOT");
        return newVersion.toString();
    }

    @SuppressWarnings("PMD.AvoidInstantiatingObjectsInLoops")
    private boolean isVersionClean(Repository repository, Path subDir,
            RevCommit taggedCommit) throws IOException, GitAPIException {
        // First, reject if there are any dirty files in the relevant directory.
        if (!VersionEvaluator.dirtyFiles(repository, subDir).isEmpty()) {
            return false;
        }
        // If the repository has no commits, it is trivially clean.
        var headId = repository.resolve("HEAD");
        if (headId == null) {
            return true;
        }
        // If the tag points to HEAD, no new commits exist to check.
        if (taggedCommit.getId().equals(headId)) {
            return true;
        }
        // Determine the base path for filtering diffs. An empty path means
        // all files are relevant.
        var taggedId = taggedCommit.getId();
        // Walk from HEAD back toward the tagged commit. For each commit,
        // diff its tree against its parent to see what changed.
        try (var revWalk = new RevWalk(repository);
                var git = new Git(repository)) {
            revWalk.markStart(revWalk.parseCommit(headId));
            for (RevCommit c : revWalk) {
                // Reached the tagged commit — all intervening commits are clean.
                if (c.getId().equals(taggedId)) {
                    break;
                }
                // Compare this commit's tree with its parent's tree.
                var oldTreeParser = new CanonicalTreeParser();
                oldTreeParser.reset(repository.newObjectReader(),
                    c.getParent(0).getTree().getId());
                var newTreeParser = new CanonicalTreeParser();
                newTreeParser.reset(repository.newObjectReader(),
                    c.getTree().getId());
                var diffs = git.diff().setNewTree(newTreeParser)
                    .setOldTree(oldTreeParser).call();
                // If any diff entry touches the relevant directory, the
                // version is no longer clean.
                for (DiffEntry diff : diffs) {
                    var newPath = Path.of(diff.getNewPath());
                    var oldPath = Path.of(diff.getOldPath());
                    if (subDir.equals(Path.of("")) || newPath.startsWith(subDir)
                        || oldPath.startsWith(subDir)) {
                        return false;
                    }
                }
            }
        }
        return true;
    }

}
