/*
 * JDrupes GitVersioning
 * Copyright (C) 2025 Michael N. Lipp
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.jdrupes.gitversioning.core;

import com.vdurmont.semver4j.Semver;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Pattern;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.lib.Repository;
import org.eclipse.jgit.revwalk.RevCommit;

/**
 * A maven style tag processor.
 * 
 * If the (latest) version found ends with "{@code -SNAPSHOT}", this
 * version is returned unchanged.
 * 
 * If the commit tagged with the version found equals {@code HEAD}
 * and no files have been changed, the version found is returned
 * unchanged.
 * 
 * Else a new version is generated by incrementing the patch number
 * of the version found, optionally appending the normalized branch
 * name and "{@code -SNAPSHOT}".
 * 
 * The branch name is omitted from the version if it matches one of the
 * patterns in ignored branches (by default "main" and "master").
 * Normalization replaces all characters except letters, numbers and
 * underscore with underscores.
 */
public class MavenStyleTagProcessor extends TagProcessorBase {

    private static final List<Pattern> DEFAULT_PATTERNS
        = List.of(Pattern.compile("main"), Pattern.compile("master"));
    private List<Pattern> ignoredBranches = new ArrayList<>();

    /**
     * Instantiates a new maven style tag processor.
     */
    public MavenStyleTagProcessor() {
        ignoredBranches.addAll(DEFAULT_PATTERNS);
    }

    /**
     * Sets the regex patterns for branch names that should be ignored.
     *
     * @param patterns the patterns
     * @return the maven style tag processor
     */
    public MavenStyleTagProcessor ignoredBranches(String... patterns) {
        ignoredBranches = new ArrayList<>(
            Arrays.stream(patterns).map(Pattern::compile).toList());
        return this;
    }

    /**
     * Adds the given regex patterns to the list of branch name patterns
     * to ignore.
     *
     * @param patterns the patterns
     * @return the maven style tag processor
     */
    public MavenStyleTagProcessor ignoreBranches(String... patterns) {
        ignoredBranches
            .addAll(Arrays.stream(patterns).map(Pattern::compile).toList());
        return this;
    }

    @Override
    public String version(Repository repository, Path subDir, RevCommit commit,
            String tagName, String version)
            throws IOException, GitAPIException {
        if (version.endsWith("-SNAPSHOT")) {
            return version;
        }
        if (commit != null && commit.equals(repository.resolve("HEAD"))
            && !isDirty(repository, subDir)) {
            return version;
        }

        // Need new version
        Semver semver
            = new Semver(version, Semver.SemverType.LOOSE).nextPatch();
        StringBuilder newVersion = new StringBuilder(semver.toString());
        var branch = repository.getBranch();
        if (!ignoredBranches.stream().map(p -> p.matcher(branch).matches())
            .filter(b -> b).findAny().isPresent()) {
            newVersion.append('-')
                .append(branch.replaceAll("[^_A-Za-z0-9]", "_"));
        }
        newVersion.append("-SNAPSHOT");
        return newVersion.toString();
    }

}
