source 'https://rubygems.org'
# gem 'github-pages', group: :jekyll_plugins
gem "jekyll", "~> 4.4"
gem "jekyll-seo-tag"
gem 'webrick', '~> 1.9', '>= 1.9.2'

gem "csv", "~> 3.3"

gem "base64", "~> 0.3.0"
